# Generated by Django 2.2.7 on 2021-01-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210126_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='project',
        ),
    ]
