# Generated by Django 2.2.7 on 2021-01-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210131_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
