# Generated by Django 2.2.7 on 2021-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20210202_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
