# Generated by Django 2.2.7 on 2021-12-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_auto_20210913_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('paypal', 'Paypal'), ('payoneer', 'Payoneer'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('toptal', 'Toptal'), ('bitcoin', 'Bitcoin')], max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('display_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
