# Generated by Django 2.2.7 on 2021-12-16 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_paymentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_platform',
        ),
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.PaymentAccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='platform',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('payoneer', 'Payoneer'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('toptal', 'Toptal'), ('bitcoin', 'Bitcoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='financial_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.FinancialRequest'),
        ),
    ]
