# Generated by Django 2.2.7 on 2021-12-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_paymentaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='display_name',
            field=models.CharField(default=7, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='platform',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('payoneer', 'Payoneer'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('toptal', 'Toptal'), ('bitcoin', 'Bitcoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_platform',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('payoneer', 'Payoneer'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('toptal', 'Toptal'), ('bitcoin', 'Bitcoin')], max_length=10),
        ),
    ]
