# Generated by Django 2.2.7 on 2021-12-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_auto_20211216_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.PaymentAccount'),
        ),
    ]
