# Generated by Django 2.2.7 on 2022-03-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_auto_20220224_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Project'),
        ),
    ]
