# Generated by Django 2.2.7 on 2022-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_project_paymentperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='paymentPeriod',
            field=models.IntegerField(blank=True, choices=[(1, 'Weekly'), (2, 'Bi-Weekly'), (3, 'Monthly')], default=1, null=True),
        ),
    ]
