# Generated by Django 2.2.7 on 2022-04-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_project_payment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrequest',
            name='requested_at',
            field=models.DateField(null=True),
        ),
    ]
