# Generated by Django 2.2.7 on 2021-08-30 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True, verbose_name='Notification message')),
                ('object_id', models.PositiveIntegerField()),
                ('read', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creators', to=settings.AUTH_USER_MODEL)),
                ('notify_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
