# Generated by Django 2.2.7 on 2021-01-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='weakly_limit',
            field=models.IntegerField(default=40),
        ),
    ]
