# Generated by Django 2.2.7 on 2021-01-24 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_project_weakly_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrequest',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finance.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrequest',
            name='requester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
