# Generated by Django 2.2.7 on 2021-01-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210124_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialrequest',
            old_name='object_id',
            new_name='counter_party_id',
        ),
        migrations.RenameField(
            model_name='financialrequest',
            old_name='content_type',
            new_name='counter_party_type',
        ),
    ]
