# Generated by Django 2.2.7 on 2021-02-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20210202_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Project'),
        ),
    ]
