# Generated by Django 2.2.7 on 2021-08-31 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date of Log'),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Created Date of Log'),
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('owner', 'created_at')},
        ),
    ]
