# Generated by Django 2.2.7 on 2021-09-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20210831_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='log_type',
        ),
        migrations.AlterField(
            model_name='log',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
