# Generated by Django 2.2.7 on 2021-09-03 05:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0003_auto_20210901_0007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('owner', 'created_at', 'interval')},
        ),
    ]
