# Generated by Django 2.2.7 on 2021-09-08 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20210903_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 9, 8), verbose_name='Created Date of Log'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.date(2021, 9, 8), verbose_name='Updated Date of Log'),
            preserve_default=False,
        ),
    ]
