# Generated by Django 2.2.7 on 2020-12-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201223_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('email', 'Email'), ('skype', 'Skype'), ('slack', 'Slack'), ('ms_team', 'MS Team'), ('github', 'Github'), ('bitbucket', 'Bitbucket')], max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('recovery_email', models.EmailField(max_length=254)),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSecurityQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Account')),
            ],
        ),
    ]
