# Generated by Django 2.2.7 on 2021-03-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210316_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_info',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
