# Generated by Django 2.2.7 on 2021-01-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201224_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('profile', 'email')},
        ),
    ]
