# Generated by Django 2.2.7 on 2021-01-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210117_0248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('profile', 'email', 'platform_type')},
        ),
    ]
