# Generated by Django 2.2.7 on 2021-03-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210202_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='recovery_email',
        ),
        migrations.AddField(
            model_name='account',
            name='extra_info',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
