# Generated by Django 2.2.7 on 2021-09-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210913_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recovery_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
