# Generated by Django 2.2.7 on 2022-01-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210918_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AccountPlatform'),
        ),
    ]
