# Generated by Django 2.2.7 on 2022-01-21 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220121_1417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('profile', 'email')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='platform_type',
        ),
    ]
