
ROLE_ADMIN = 1
ROLE_TEAM_MANAGER = 2
ROLE_DEVELOPER = 3

ROLE_TYPES = [
    (ROLE_ADMIN, 'admin'),
    (ROLE_TEAM_MANAGER, 'team manager'),
    (ROLE_DEVELOPER, 'developer')
]

PROFILE_TYPE_SELF = 1
PROFILE_TYPE_PARTNER = 2

PROFILE_TYPES = [
    (PROFILE_TYPE_SELF, 'self'),
    (PROFILE_TYPE_PARTNER, 'partner')
]

PROFILE_GENDER_MALE = 1
PROFILE_GENDER_FEMALE = 2

PROFILE_GENDERS = [
    (PROFILE_GENDER_MALE, 'male'),
    (PROFILE_GENDER_FEMALE, 'female')
]
